version: '3'
services:
  database:
    image: mongo:latest
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE_NAME}
    ports:
      - 27017:27017
    volumes:
      - database_data:/data/db

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm start:dev reservations
    container_name: reservations
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
volumes:
  database_data:
