version: '3'
services:
  database:
    image: mongo:latest
    container_name: 'database'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - database_data:/data/db

volumes:
  database_data:
