version: '3'
services:
  database:
    image: mongo:latest
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: sleepr
    ports:
      - 27017:27017
    volumes:
      - database_data:/data/db

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm start:dev reservations
    container_name: reservations
    depends_on:
      - database
    ports:
      - 3000:3000
    env_file:
      - ./apps/reservations/.env
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    container_name: auth
    depends_on:
      - database
    ports:
      - 3001:3001
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm start:dev payments
    container_name: payments
    depends_on:
      - database
    ports:
      - 3003:3003
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app

volumes:
  database_data:
